# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.author.title }}, {{ site.author.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Sam Scherer
author: 
  name: Sam Scherer
  pronouns: He/Him
  email: sam.r.scherer@gmail.com
# description: >- # this means to ignore newlines until "baseurl:"
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  swiimii
itch-dot-io_username: swiimii

minima:
  skin: dark
  nav_pages:
    - _pages/aboutme.markdown
    - _pages/featuredProjects.markdown
    - _pages/allProjects.markdown
    - _pages/resume.markdown
  social_links:
    - title: LinkedIn
      icon: linkedin
      url: "https://www.linkedin.com/in/samuel-scherer2/"
    - title: Github
      icon: square-github
      url: "https://github.com/swiimii"
    - title: Itch.io
      url: "https://swiimii.itch.io"
      icon: itch-io
    - title: Devpost
      url: "https://devpost.com/swiimii"
      icon: dev
  hide_site_feed_link: true


# Build settings
# theme: minima
plugins:
  - jekyll-remote-theme

remote_theme: jekyll/minima

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
